apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dockyards-pdns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dockyards-pdns
subjects:
  - kind: ServiceAccount
    name: dockyards-pdns
