apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockyards-pdns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dockyards-pdns
      app.kubernetes.io/part-of: dockyards
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dockyards-pdns
        app.kubernetes.io/part-of: dockyards
      name: dockyards-pdns
    spec:
      containers:
        - image: dockyards-pdns
          name: dockyards-pdns
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          args:
            - --dockyards-namespace=$(METADATA_NAMESPACE)
          env:
            - name: METADATA_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      imagePullSecrets:
        - name: dockyards-registry
      serviceAccountName: dockyards-pdns
      securityContext:
        fsGroup: 65532
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
